version: '3.7'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lamp

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    restart: always
    ports:
      - 8080:80

  nginx:
    build: ./docker/nginx/
    depends_on:
      - db
    ports:
      - 8000:80
    volumes:
      # - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      # - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./log:/var/log/nginx
      - ./code:/usr/share/nginx/html

  php:
    image: phpdockerio/php73-fpm
    depends_on:
      - db